name = "NonlinearSystemSurrogate"
uuid = "d1b8fcc4-fbc0-4b0d-83d7-b69010db5954"
authors = ["Felix Brandt"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
